# Meta Data for SEO

## Homepage
description = "focuses on and researches computer open source technology, and aims to use open source to give back to open source."
title = "AcmeStack"
titleAddition = "The Opening Technology Observer"
titleSeparator = "-"

## Documentation
docsVersion = "v0.0.1"

## Open Graph
domainTLD = "acmestack.com"
images = ["acmestack.png"]
ogLocale = "zh_CN"
titleHome = "AcmeStack Community"

## JSON-LD
# schemaType = "Person"
schemaAuthor = "qicz"
schemaAuthorGitHub = "https://github.com/acmestack"
schemaGitHub = "https://github.com/acmestack"
schemaImage = "acmestack.png"
schemaImageHeight = 640
schemaImageWidth = 1280
schemaLinkedIn = ""
schemaLocale = "en-US"
schemaLogo = "acmestack-logo.png"
schemaLogoHeight = 512
schemaLogoWidth = 512
schemaName = "AcmeStack"
schemaSection = "blog"
schemaType = "Organization"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
lqipWidth = "20x"
portraitPhotoWidths = [800, 700, 600, 500]
quality = 85
smallLimit = "300"

# Footer
footer = "Copyright © 2013-2022 <a class=\"text-muted\" href=\"https://acmestack.com/\">AcmeStack</a> All rights reserved."

# Feed
copyRight = "Copyright (c) 2013-2022 AcmeStack All rights reserved."

# Alert
alert = false
alertDismissable = true
alertText = "focuses on and researches computer open source technology, and aims to use open source to give back to open source."

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/acmestack/acmestack-website"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

[options]
bootStrapJs = true
breadCrumb = true
clipBoard = true
darkMode = true
docsVersioning = true
flexSearch = true
fullWidth = false
highLight = true
instantPage = true
kaTex = false
lazySizes = true
multilingualMode = true

[menu]
[menu.section]
auto = true
collapsibleSidebar = true
